version: "3.8"
services:
  server:
    container_name: nestjs_prisma_server_s1
    build: ./app
    tty: true
    depends_on:
      - db
    volumes: # ローカルとコンテナのパスをマウント
      - ./app:/app
      - /etc/localtime:/etc/localtime:ro # タイムゾーンを日本時刻に設定
    working_dir: /app
    environment:
      TZ: Asia/Tokyo # タイムゾーンを日本時刻に設定
    #command: sh -c 'yarn && yarn start'
    ports:
      - 4000:4000
    security_opt:
      - seccomp:unconfined

  db:
    container_name: nestjs_prisma_db_s1
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - "TZ=Asia/Tokyo" # タイムゾーンを日本時刻に設定
    image: mysql:8
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    volumes:
      - graphql_db_data:/var/lib/mysql
      - ./mysql/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
    ports:
      - 3306:3306

volumes:
  graphql_db_data:
